[tool.poetry]
name = "project2"
version = "0.1.0"
description = ""
authors = ["Mathieu Haage <mahaage@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
shared = { path = "../shared" }


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
